name: Test nix-diff-action

on:
  pull_request:

jobs:
  full:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-nix
      - name: Run nix-diff-action
        uses: ./
        with:
          attributes: |
            - displayName: devShell
              attribute: devShells.x86_64-linux.default
